import Head from "next/head";
import { useContext } from "react";
import { Context } from "../../context/UserContext";
import Login from "../../pages/Login";
import HeaderPage from "../Header";
import SideBar from "../SideBar";
import { Wrapper, BlackMirror} from "./style";
import imfine from "../../assets/icons/im-fine.svg";
import Image from "next/image";

const Page = ({ children }) => {
  const { user, loading } = useContext(Context);

  if(loading){
    return <BlackMirror>
      <Image src={imfine} width={500} height={500}/>
    </BlackMirror>
  }

  return (
    <div className="wrapper">
      <Head>
        <title>CodeBrain</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="./ico/logo.svg" /> */}
      </Head>
      {user ? (
        <>
          <HeaderPage />
          <Wrapper>
            <SideBar />
            <main className="page container">{children}</main>
          </Wrapper>
        </>
      ) : (
        <Login />
      )}
    </div>
  );
};

export default Page;
