import { useContext } from "react";
import Head from "next/head";
import Image from "next/image";
import { Context } from "../../context/UserContext";
import Login from "../../pages/Login";
import HeaderPage from "../Header";
import SideBar from "../SideBar";
import { Wrapper, BlackMirror} from "./style";
import { imfine } from "../../assets";

const Page = ({ children , title = 'CodeBrain'}) => {
  const { user, loading } = useContext(Context);

  if(loading){
    return <BlackMirror>
      <Image src={imfine} width={500} height={500} alt="imfine"/>
    </BlackMirror>
  }

  return (
    <div className="wrapper">
      <Head>
        <title>CodeBrain</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="./ico/logo.svg" /> */}
      </Head>
      {user ? (
        <>
          <HeaderPage />
          <Wrapper>
            <SideBar />
            <main className="page container">{children}</main>
          </Wrapper>
        </>
      ) : (
        <Login />
      )}
    </div>
  );
};

export default Page;
